language: cpp

# Downloading the latest cmake that the issue appears
before_install:
 - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh 
 - mkdir /tmp/cmakebin
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/tmp/cmakebin
 
script:
     - mkdir -p build
     - cd build
     - /tmp/cmakebin/bin/cmake .. 
