language: cpp

before_install:
 - cd /tmp
 - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh 
 - mkdir cmakebin
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/tmp/cmakebin
 
script:
     - mkdir -p build
     - cd build
     - /tmp/cmakebin/bin/cmake .. 
